### ISSUE TITLE
Unable to parse when optional fields are missing

### ISSUE THREAD

**Issue by jhrcek** [freizl/har#3]
Hello,

thanks for this library, I find it useful! It's working perfectly when browsing har files saved by google-chrome. However when parsing har from firefox, I'm occasionally getting the following errors:
```
Left "Error in $.timings: When parsing the record Timings of type HAR.Timings.Timings the key ssl was not present."
```
Here's more or less [standalone reproducer](https://gist.github.com/jhrcek/b0dfddbe8880be565c04c39588e7dda3) - using data extracted from HAR file saved from firefox session.

When looking at [HAR 12 spec](http://www.softwareishard.com/blog/har-12-spec/#timings), I see that the missing field is actually optional. Could you please declare those fields marked as Optional using Maybe to make this kind of (valid according to spec) files parseable?

**Comment by freizl** [comment]
verify your example and it produces `Right` value.
let me if still problems.

http://hackage.haskell.org/package/har-0.4.0

**Comment by jhrcek** [comment]
Thanks for the fix! Now it's working fine :-)
