### ISSUE TITLE
.har files not parsing

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [freizl/har#5]
Similar to #3. har file from Firefox is not parsed

```haskell
Left "Error in $.log.pages[0]: When parsing the record Page of type HAR.Page.Page the key title was not present."
```

**Comment by freizl** [comment]
Are you suggesting `Page.title` is optional?

**Comment by freizl** [comment]
doesn't seem `title` is optional from spec. http://www.softwareishard.com/blog/har-12-spec
curious what page you are testing or maybe shared the HAR file?
